classes: {
  ВерховнТроичнЛичности: {
    width: 200
    height: 100
    style: {
      # stroke-width: 0
      fill: "#e5cce5"
      # shadow: true
      # border-radius: 5
    }
  }

  НисходящиеСыны: {
    shape: image
    icon: https://img.icons8.com/sf-ultralight/100/give-way.png
    # https://img.icons8.com/glyph-neue/64/give-way.png
  }
  Духи: {
    shape: oval
    style: {
      stroke: orange
      fill: "#ffd27f"
    }
  }
  ПопечительскиеДухи: {
    shape: image
    icon: https://img.icons8.com/external-basicons-color-danil-polshin/50/external-christmas-christmas-basicons-color-danil-polshin-10.png
    # icon: https://img.icons8.com/ios/50/angel-with-sword.png
    style: {
      stroke: orange
      fill: "#ffd27f"
    }
  }
  ОтражДухи: {
    shape: image
    icon: https://img.icons8.com/ios/50/000000/fitting-room.png
    # icon: https://img.icons8.com/external-outline-black-m-oki-orlando/32/000000/external-reflection-physics-basic-outline-outline-black-m-oki-orlando.png
    # icon: https://img.icons8.com/external-others-pike-picture/50/external-clinic-plastic-surgery-clinic-others-pike-picture-4.png
    style: {
      stroke: orange
      fill: "#ffd27f"
      multiple: true
    }
  }
  ЭнергЦентры: {
    shape: diamond
    style: {
      stroke: pink
      fill: pink
    }
  }
  Структура: {
    label.near: top-left
    top: 200
    left: 300
    direction: down
  }
}

МетВс: Большая Вселенная {
  direction: down
  style: {
    stroke: blue
    fill: "#a6b9f2" # hsl(225, 74%, 85%)
  }
  Всеобщий-Абсолют: {
    # near: МетВс.Божество-Абсолют
    Божество-Абсолют: Условный Абсолют
    Безусловный-Абсолют # .near: МетВс.Божество-Абсолют
  }
  ТворцыСовокупнойВселенной: Творцы Совокупной Вселенной
  ТрансцендентальныеРегистраторы: Трансцендентальные Регистраторы {
    near: МетВс.Всеобщий-Абсолют
  }
  ПервичныеВозникшиеГлавныеОрганизаторыСил: Первичные Возникшие\nГлавные Организаторы Сил {
    class: ЭнергЦентры
  }
  АссоциированныеТрансцендентальныеГлавныеОрганизаторыСил: {
    label: Ассоциированные Трансцендентальные\nГлавные Организаторы Сил
    class: ЭнергЦентры
  }
  ОдиночныеПосланники: Одиночные\nПосланники {class: Духи}
  ВдохновенныеТроичныеДухи: Вдохновенные\nТроичные Духи {class: Духи}
  СмотрителиВселенскихКонтуров: Смотрители\nВселенских\nКонтуров {class: Духи}
  РегистраторыВолевыхСозданий: Регистраторы\nВолевых\nСозданий {class: Духи}
  ЛичныеПомощникиБесконечногоДуха: Личные Помощник\nБесконечного Духа {class: Духи}
  ГлавныеФизическиеРегуляторы: Главные\nФизические Регуляторы {
    label.near: top-center
    direction: down
    # class: ЭнергЦентры
    АссоциированныеУправляющиеЭнергией: 1. Ассоциированные\nуправляющие энергией {
      class: ЭнергЦентры
    }
    МеханическиеРегуляторы: 2. Механические регуляторы {class: ЭнергЦентры}
    ПреобразователиЭнергии: 3. Преобразователи энергии {class: ЭнергЦентры}
    ПередатчикиЭнергии: 4. Передатчики энергии {class: ЭнергЦентры}
    ПервичныеОбъединители: 5. Первичные объединители {class: ЭнергЦентры}
    ВторичныеРазъединители: 6. Вторичные разъединители {class: ЭнергЦентры}
    ФрандаланкиХронолдеки: 7. Франдаланки и хронолдеки {class: ЭнергЦентры}
    АссоциированныеУправляющиеЭнергией -- МеханическиеРегуляторы -- ПреобразователиЭнергии -- ПередатчикиЭнергии -- ПервичныеОбъединители -- ВторичныеРазъединители -- ФрандаланкиХронолдеки
  }
  Рай -> Хавона -> СвВс
  (Рай.Троица.БесконечныйДух -> ОдиночныеПосланники).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> СмотрителиВселенскихКонтуров).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> РегистраторыВолевыхСозданий).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> ЛичныеПомощникиБесконечногоДуха).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> СвВс.Тертиафимы).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> СвВс.Омниафимы).style.stroke: orange
  (Рай.7ВерхАдминов -> СвВс.Омниафимы).style.stroke: orange

  (Рай.Троица.БесконечныйДух -> Хавона.ПроводникиСмертныхКандидатов).style.stroke: orange
  (Рай.7ГлДухов -> Хавона.ВторичнСупернафимы).style.stroke: orange
  (Рай.7ГлДухов -> Хавона.ВерховныеЭнергетическиеЦентры).style.stroke: pink
  (Рай.ВерховныеУправляющиеЭнергией -> Хавона.ВерховныеЭнергетическиеЦентры).style.stroke: pink
  (Хавона.ВерховныеЭнергетическиеЦентры -> ГлавныеФизическиеРегуляторы).style.stroke: pink
  (Рай.ВерховныеУправляющиеЭнергией -> ГлавныеФизическиеРегуляторы.ПреобразователиЭнергии).style.stroke: pink

  (Рай.Троица.БесконечныйДух -> СвВс.БСек.МСек.ЛокВс.АссоциированныеИнспекторы).style.stroke: orange
  (Рай.7ГлДухов -> СвВс.БСек.МСек.ЛокВс.АссоциированныеИнспекторы).style.stroke: orange

  (Рай.Троица.БесконечныйДух -> СвВс.БСек.МСек.ЛокВс.Авоналы).style.stroke: orange
  (Рай.Троица.ВечныйСын -> СвВс.БСек.МСек.ЛокВс.Авоналы).style.stroke: blue

  (Рай.Троица.ВсеобщийОтец -> СвВс.БСек.МСек.ЛокВс.Дайналы).style.stroke: red
  (Рай.Троица.ВечныйСын -> СвВс.БСек.МСек.ЛокВс.Дайналы).style.stroke: blue
  (Рай.Троица.БесконечныйДух -> СвВс.БСек.МСек.ЛокВс.Дайналы).style.stroke: orange
  (Рай.Троица.БесконечныйДух -> СвВс.БСек.МСек.ЛокВс.Созвездие.Система.ПолномочныеСтражи).style.stroke: orange
  (Рай.Троица -> ВдохновенныеТроичныеДухи).style.stroke: "#a64ca6"
  (Рай.Троица -> Хавона.ВечныеДней).style.stroke: "#a64ca6"

  (Рай.Троица -> СвВс.ДревниеДней).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.СвершителиМудрости).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.БожественныеСоветники).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.ВсеобщиеЦензоры).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.БСек.СовершенстваДней).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.БСек.МСек.НедавниеДней).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.БСек.МСек.ЛокВс.СоюзыДней).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.БСек.МСек.ЛокВс.Созвездие.ВерныеДней).style.stroke: "#a64ca6"
  (Рай.Троица -> СвВс.ОтражательныеДухи).style.stroke: "#a64ca6"
  (Рай.Мажестон -> СвВс.ОтражательныеДухи).style.stroke: orange
  (СвВс.ОтражательныеДухи -> СвВс.ВспомогательныеОбразыОтражения).style.stroke: orange
  (Рай.7ГлДухов -> СвВс.ОтражательныеДухи).style.stroke: orange
  Всеобщий-Абсолют.Божество-Абсолют -> Рай.Мажестон <- СвВс.ВерховноеСущество
  (Рай.Троица.БесконечныйДух -> Хавона.7КольцевыхДухов <- Рай.7ГлДухов).style.stroke: orange
  Рай.Супруги.Сыны-Создатели -> СвВс.БСек.МСек.ЛокВс.Супруги.Михаилы: {
    style: {
      stroke: red
      stroke-dash: 3
      # animated: true
    }
  }
  Рай.Супруги.МатеринскийДух -> СвВс.БСек.МСек.ЛокВс.Супруги.БожественнаяПопечительница: {
    style: {
      stroke: orange
      stroke-dash: 3
      # animated: true
    }
  }
  СвВс.ДревниеДней -> СвВс.БСек.МСек.ЛокВс.НосителиЖизни
  (Рай.Троица.ВсеобщийОтец -> СвВс.БСек.МСек.ЛокВс.Созвездие.Система.ОбитМир.Смертные.Тело.Разум.Настройщик).style.stroke: red
}

МетВс.Рай: {
  label.near: top-left
  top: 0
  left: 0
  # shape: oval
  # width: 5000 # Не работает для имеющих вложение
  # height: 400
  style: {
    fill: yellow
    shadow: true
    font-size: 100
  }
  Троица: {
    direction: right
    top: 0
    left: 0
    style: {
      fill: "#d8b2d8"
    }
    ВсеобщийОтец: Всеообщий\nОтец {
      tooltip: Первый Источник И Центр
      # link: http://urantiaexplorer.org/.U1_0_1
      top: 0
      left: 0
      width: 200
      height: 100
      style: {
        stroke: red
        fill: "#ffb2b2"
        # opacity: 0.4
      }
    }
    ВечныйСын: Вечный\nСын {
      top: 0
      left: 300
      width: 200
      height: 100
      style: {
        stroke: blue
        fill: "#b2b2ff"
      }
    }
    БесконечныйДух: Бесконечный\nДух {
      class: Духи
      top: 0
      left: 600
      width: 200
      height: 100
      style: {
        stroke: orange
        fill: "#ffd27f"
      }
    }
    ВсеобщийОтец -- ВечныйСын: {style: {opacity: 0}}
    ВечныйСын -- БесконечныйДух: {style: {opacity: 0}}
  }
  Тринитизованныетайны: Тринитизованные\nтайны верховности {
    class: ВерховнТроичнЛичности
  }
  #  Тринитизованныетайны.class: ВерховнТроичнЛичности
  #  Тринитизованныетайны.label: Тринитизованные\nтайны верховности

  7ГлДухов: 7\nГлавных Духов {class: Духи}
  Супруги: {
    direction: right
    Сыны-Создатели: Сыны\nСоздатели {
      top: 0
      left: 0
      class: НисходящиеСыны
    }
    МатеринскийДух: Материнский\nДух {
      top: 0
      left: 300
      class: Духи
    }
  }
  ВерховныеУправляющиеЭнергией: Верховные\nУправляющие Энергией {class: ЭнергЦентры}
  7ВерхАдминов: Семь\nВерховных Администраторов
  Мажестон: {class: ОтражДухи}
  ПервичнСупернафимы: Первичные\nСупернафимы {class: ПопечительскиеДухи}
  (Троица.БесконечныйДух -> 7ГлДухов).style.stroke: orange
  (Троица.БесконечныйДух -> 7ВерхАдминов).style.stroke: orange
  (7ГлДухов -> ВерховныеУправляющиеЭнергией).style.stroke: pink
  (Троица.ВсеобщийОтец -> Супруги.Сыны-Создатели).style.stroke: red
  (Троица.ВечныйСын -> Супруги.Сыны-Создатели).style.stroke: blue
  (Троица.БесконечныйДух -> ПервичнСупернафимы).style.stroke: orange
  (7ГлДухов -> Супруги.МатеринскийДух).style.stroke: orange
  (Троица -> Тринитизованныетайны).style.stroke: "#a64ca6"
}
МетВс.Хавона: {
  label.near: top-left
  style: {
    stroke: blue
    fill: "#cad5f7" # hsl(225, 74%, 88%)
    font-size: 100
  }
  top: 1200
  left: 0
  ВечныеДней: Вечные\nДней {class: ВерховнТроичнЛичности}
  7КольцевыхДухов: Семь\nКольцевых Духов {class: Духи}
  ВерховныеЭнергетическиеЦентры: Верховные\nЭнергетические Центры {class: ЭнергЦентры}
  ВторичнСупернафимы: Вторичные\nСупернафимы {
    class: ПопечительскиеДухи
    # shape: image
    # icon: https://telegra.ph/file/c8906d91b7442ba7f294c.png
  }
  ТретичныеСупернафимы: Третичные\nСупернафимы {class: ПопечительскиеДухи}
  ПроводникиСмертныхКандидатов: Проводники\nСмертных Кандидатов {class: Духи}
  (7КольцевыхДухов -> ТретичныеСупернафимы).style.stroke: orange
}

МетВс.СвВс: Сверхвселенная {
  style: {
    stroke: blue
    fill: "#cad5f7" # hsl(225, 74%, 88%)
    font-size: 100
  }
  label.near: top-left
  top: 2300
  left: 0
  direction: down
  ОтражательныеДухи: Отражательные\nДухи {class: ОтражДухи}
  Секонафимы: {class: ОтражДухи}
  Тертиафимы: {class: ПопечительскиеДухи}
  Омниафимы: {class: ПопечительскиеДухи}
  (ОтражательныеДухи -> Секонафимы).style.stroke: orange

  ВспомогательныеОбразыОтражения: Вспомогательные\nОбразы Отражения {class: ОтражДухи}
  ДревниеДней: Древние\nДней {class: ВерховнТроичнЛичности}
  СвершителиМудрости: Свершители\nМудрости {class: ВерховнТроичнЛичности}
  БожественныеСоветники: Божественные\nСоветники {class: ВерховнТроичнЛичности}
  ВсеобщиеЦензоры: Всеобщие\nЦензоры {class: ВерховнТроичнЛичности}

  БСек: Большой сектор {
    style: {
      stroke: blue
      fill: "#d7e0f9" # hsl(225, 74%, 91%)
      font-size: 95
    }
    class: Структура
    СовершенстваДней: Совершенства\nДней {class: ВерховнТроичнЛичности}
    МСек: Малый сектор {
      style: {
        stroke: blue
        fill: "#dce3fa" # hsl(225, 74%, 92%)
        font-size: 90
      }
      class: Структура
      НедавниеДней: Недавние\nДней {class: ВерховнТроичнЛичности}
      ЛокВс: Локальная вселенная {
        style: {
          stroke: blue
          fill: "#e0fae0" # hsl(120, 74%, 93%)
          font-size: 85
        }
        class: Структура
        СоюзыДней: Союзы Дней\n(Иммануил) {class: ВерховнТроичнЛичности}
        АссоциированныеИнспекторы: Ассоциированные\nИнспекторы {class: Духи}
        Авоналы: Сыны\nАвоналы {class: НисходящиеСыны}
        Дайналы: Сыны\nДайналы {
          near: МетВс.СвВс.БСек.МСек.ЛокВс.Авоналы
          class: НисходящиеСыны
        }
        ОтецМелхиседек: Отец-Мелхиседек {class: НисходящиеСыны}
        НосителиЖизни: Носители\nЖизни {class: НисходящиеСыны}
        СветлаяУтренняяЗвезда: Светлая Утренняя Звезда\n(Гавриил)
        ЯркиеВечерниеЗвезды: Яркие Вечерние Звезды
        Серафимы: {class: ПопечительскиеДухи}
        Херувимы: {class: ПопечительскиеДухи}
        Сановимы: {class: ПопечительскиеДухи}
        ВспомДухиРазума: Вспомогательные\nДухи Разума {
          label.near: top-center
          class: Духи
          ДухИнтуиции: 1. Дух Интуиции {class: Духи}
          ДухПонимания: 2. Дух Понимация {class: Духи}
          ДухОтваги: 3. Дух Отваги {class: Духи}
          ДухЗнания: 4. Дух Знания {class: Духи}
          ДухСовета: 5. Дух Совета {class: Духи}
          ДухПоклонения: 6. Дух Поклонения {class: Духи}
          ДухМудрости: 7. Дух Мудрости {class: Духи}
        }
        (Супруги.БожественнаяПопечительница -> Серафимы).style.stroke: orange
        (Супруги.БожественнаяПопечительница -> Херувимы).style.stroke: orange
        (Супруги.БожественнаяПопечительница -> Сановимы).style.stroke: orange
        (Супруги.БожественнаяПопечительница -> ВспомДухиРазума).style.stroke: orange
        Супруги -> НосителиЖизни
        Супруги -> Сузаты
        Супруги -> Унивитаты
        Супруги.Михаилы -> Созвездие.Система.МатериальныеСыны
        Супруги -> СветлаяУтренняяЗвезда
        Супруги -> ЯркиеВечерниеЗвезды
        Супруги -> Архангелы
        Супруги -> ОтецМелхиседек

        Супруги -> Созвездие.Мелхиседеки
        ОтецМелхиседек -> Созвездие.Мелхиседеки
        Супруги -> Созвездие.Ворондадеки
        Супруги -> Созвездие.Система.Ланонандеки

        Супруги: {
          Михаилы: Сыны\nМихаилы {class: НисходящиеСыны}
          БожественнаяПопечительница: Божественная\nПопечительница {class: Духи}
        }
        Созвездие: {
          class: Структура
          style: {
            stroke: blue
            fill: "#e9fce9" # hsl(120, 74%, 95%)
            font-size: 80
          }
          ВерныеДней: Верные\nДней {
            # near: top-center
            class: ВерховнТроичнЛичности
          }
          Мелхиседеки: {class: НисходящиеСыны}
          Ворондадеки: {class: НисходящиеСыны}
          Мелхиседеки -> Система.Мидсониты
          Система.МатериальныеСыны.Евы -> Система.Мидсониты

          Система: {
            class: Структура
            style: {
              stroke: blue
              fill: "#f2fdf2" # hsl(120, 74%, 97%)
              font-size: 60
            }
            ПолномочныеСтражи: Полномочные\nСтражи {class: Духи}
            Ланонандеки: {
              near: МетВс.СвВс.БСек.МСек.ЛокВс.Созвездие.Ворондадеки
              class: НисходящиеСыны
            }
            МатериальныеСыны: Материальные Сыны и Дочери {
              # class: НисходящиеСыны
              Адамы
              Евы
            }
            Мидсониты
            Ланонандеки -> ОбитМир.ПланетарныйКнязь: {
              style: {
                stroke-dash: 3
                # animated: true
              }
            }

            МатериальныеСыны.Адамы -> ОбитМир.Адам: {
              style: {
                stroke-dash: 3
                # animated: true
              }
            }
            МатериальныеСыны.Евы -> ОбитМир.Ева: {
              style: {
                stroke-dash: 3
                # animated: true
              }
            }

            ОбитМир: Обитаемый мир {
              class: Структура
              style: {
                stroke: blue
                fill: "#fbfefb" # hsl(120, 74%, 99%)
                font-size: 50
              }
              ПланетарныйКнязь: Планетарный\nКнязь {
                top: 0
                left: 0
                class: НисходящиеСыны
              }
              Смертные: {
                style: {
                  stroke: blue
                  fill: "#f2f5fd" # hsl(225, 74%, 97%)
                }
                Тело: {
                  # shape: image
                  # icon: https://img.icons8.com/ios/50/standing-man.png
                  style: {
                    stroke: blue
                    fill: "#f6f8fe" # hsl(225, 74%, 98%)
                  }
                  Разум: {
                    style: {
                      stroke: blue
                      fill: "#fbfcfe" # hsl(225, 74%, 99%)
                    }
                    Настройщик: {
                      style: {
                        stroke: red
                      }
                    }
                  }
                }
              }
              Промежуточные: Промежуточные\nсоздания
            }
          }
        }
      }
    }
  }
}
# МетВс.Рай.Тринитизованныетайны -> МетВс.Хавона.ВечныеДней
# МетВс.Хавона.ВечныеДней -> МетВс.СвВс.ДревниеДней
# МетВс.СвВс.ДревниеДней -> МетВс.СвВс.БСек.СовершенстваДней
# МетВс.СвВс.БСек.СовершенстваДней -> МетВс.СвВс.БСек.МСек.НедавниеДней
# МетВс.СвВс.БСек.МСек.НедавниеДней -> МетВс.СвВс.БСек.МСек.ЛокВс.СоюзыДней
